### ISSUE TITLE
Errors in Google Search, Google Images and YouTube

### ISSUE THREAD

**Issue by koodoxz** [Telegram-Bot-Node/Nikoro#129]
Hi

How can i enable plugin google search? I've searched the wiki but did not find it.
if i enable the plugin and show error like this : 

warn: [PluginManager] Failed to initialize plugin GoogleSearch.

Thanks

**Comment by crisbal** [comment]
Hello, as you can see from here (as of right now I am not sure it is documented) https://github.com/crisbal/Telegram-Bot-Node/blob/es6/src/plugins/GoogleSearch.js#L23 you need to provide the Google API Key and the Google CX Key that you can get using Google API Console (https://console.cloud.google.com/?pli=1) in the config.json file

**Comment by crisbal** [comment]
Ok I just checked and it seems the issues is on our side. I will keep you updated when we fix the problem

**Comment by CapacitorSet** [comment]
By the way, @koodoxz do you have a complete log? Are there other lines explaining the error?

**Comment by koodoxz** [comment]
Hi 

@CapacitorSet Here is the log when in **Firstrun**
-  GoogleSearch.js (Cannot find module 'this.google-search')
-  Wordgame.js (Cannot find module 'word-list')
-  YouTube.js (Cannot find module 'youtube-api')

and here are the full log

 npm run bot

> telegram-bot-node@1.0.0 bot /home/Telegram-Bot-Node
> node src/Bot.js

info: [Bot] Instance created.
node-telegram-bot-api deprecated Events new_chat_participant,left_chat_participant are deprecated. See the updated list of events: https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#events src/PluginManager.js:35:17
warn: [PluginManager]  Error: Cannot find module 'this.google-search'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Telegram-Bot-Node/src/plugins/GoogleSearch.js:2:22)
warn: [PluginManager] Failed to initialize plugin GoogleSearch.
warn: [PluginManager]  Error: Cannot find module 'youtube-api'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Telegram-Bot-Node/src/plugins/YouTube.js:2:17)
warn: [PluginManager] Failed to initialize plugin YouTube.
warn: [PluginManager] Some plugins couldn't be loaded.
info: [Bot] Plugins loaded.
info: [Bot] Permissions configured.
info: [Bot] The bot is online!
^Cwarn: [Bot] Shutting down, reason: SIGINT received
info: [Bot] Stopping safely all the plugins...
info: [Bot] All plugins stopped correctly.

**Comment by CapacitorSet** [comment]
I pushed 544c09b, that should fix it. Can you `git pull` and try again?

**Comment by CapacitorSet** [comment]
Actually, I just pushed another bugfix in 1b2d1ca - you should try pulling once again, if you already did.

**Comment by koodoxz** [comment]
Hi @CapacitorSet 

thank you for fast respon, i think still cant find module for google search, here is the log

warn: [PluginManager]  Error: Cannot find module 'google-search'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Telegram-Bot-Node/src/plugins/GoogleSearch.js:2:22)
warn: [PluginManager] Failed to initialize plugin GoogleSearch.

**Comment by CapacitorSet** [comment]
Oh, in that case, you'll just need to install it: `npm install google-search`.

**Comment by koodoxz** [comment]
Ok noted, let me try it, thanks

**Comment by koodoxz** [comment]
Hi

just try to running, but still found this error

info: [Bot] Plugins loaded.
info: [Bot] Permissions configured.
info: [Bot] The bot is online!
error: [Bot]  TypeError: Cannot read property 'sendMessage' of undefined
    at /home/Telegram-Bot-Node/src/plugins/GoogleSearch.js:49:17
    at IncomingMessage.<anonymous> (/home/Telegram-Bot-Node/node_modules/google-search/lib/google-search.js:64:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
warn: [Bot] Shutting down, reason: Uncaught exception
info: [Bot] Stopping safely all the plugins...
info: [Bot] All plugins stopped correctly.

**Comment by CapacitorSet** [comment]
Hm. Try pulling and running it now?

**Comment by koodoxz** [comment]
Thanks for the quick respons
may i ask you again, how to define call command to google search and google image in bot?

**Comment by CapacitorSet** [comment]
Simply edit src/plugins/GoogleSearch.js and src/plugins/ImageSearch.js.

For example, at [line 34 of GoogleSearch.js](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/src/plugins/GoogleSearch.js#L34) you will find `if (command !== "google") return;`, just change that command.

**Comment by koodoxz** [comment]
while i put help on bot, its show something like this

**/help**
Google Images search: Search for images on Google.
Google: Search on Google.

**/help Google Images search**
Google - Search on Google.
/google query

**/help google**
Google - Search on Google.
/google query

Edit : 

found the script that you said before

thanks

**Comment by CapacitorSet** [comment]
Thank you for your report. I'm closing this issue as fixed.

**Comment by koodoxz** [comment]
one moment please

i found another error on youtube plugin, i think is the same error with google search

info: [Bot] Plugins loaded.
info: [Bot] Permissions configured.
info: [Bot] The bot is online!
error: [Bot]  TypeError: Cannot read property 'sendMessage' of undefined
    at /home/Telegram-Bot-Node/src/plugins/YouTube.js:43:17
    at Request._callback (/home/Telegram-Bot-Node/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/home/Telegram-Bot-Node/node_modules/google-auth-library/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/Telegram-Bot-Node/node_modules/google-auth-library/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/Telegram-Bot-Node/node_modules/google-auth-library/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
warn: [Bot] Shutting down, reason: Uncaught exception
info: [Bot] Stopping safely all the plugins...
info: [Bot] All plugins stopped correctly.

**Comment by CapacitorSet** [comment]
Oh shit, indeed. I also fixed that.

I ran a quick check against the other plugins, there shouldn't be any more issues like that.

**Comment by koodoxz** [comment]
Well Noted, Thank you for the quick respons :1st_place_medal:

**Comment by koodoxz** [comment]
Hi i found error again on plugin youtube, should i paste here or i open new issue?

**Comment by CapacitorSet** [comment]
No way to tell without seeing the problem :)

If you think it's the same type of error, post on this issue; otherwise,
open a new issue.

Anyway, I'm going to bed now. It's 4 AM here in Italy, so it might be a
while before @crisbal or I can take a look.

Il 26/set/2017 04:02 AM, "koodoxz" <notifications@github.com> ha scritto:

**Comment by koodoxz** [comment]
ok, take your time, Have a good rest :1st_place_medal:

**Comment by CapacitorSet** [comment]
@koodoxz, do you have updates on the issue?

**Comment by koodoxz** [comment]
Hi @CapacitorSet sorry for late reply

here is the log when i try to find song on youtube with 32 characters including space ex : **/yt andra and the backbone - hitamku** also with this one, **/yt asd** it wont work

info: [Bot] Plugins loaded.
info: [Bot] Permissions configured.
info: [Bot] The bot is online!
error: [Bot] Unhandled rejection at Promise  Promise {
  _bitField: 18087936,
  _fulfillmentHandler0:
   { Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 92
       at BaseError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:10:5)
       at TelegramError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:56:5)
       at request.then.err (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
       at tryCatcher (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:512:31)
       at Promise._settlePromise (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:693:18)
       at Async._drainQueue (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:133:16)
       at Async._drainQueues (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:143:10)
     code: 'ETELEGRAM',
     response:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        request: [Object],
        toJSON: [Function: responseToJSON],
        caseless: [Object],
        read: [Function],
        body: [Object] } },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _cancellationParent:
   Promise {
     _bitField: 16777216,
     _fulfillmentHandler0:
      { Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 92
          at BaseError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:10:5)
          at TelegramError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:56:5)
          at request.then.err (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
          at tryCatcher (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/util.js:16:23)
          at Promise._settlePromiseFromHandler (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:512:31)
          at Promise._settlePromise (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:569:18)
          at Promise._settlePromise0 (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:614:10)
          at Promise._settlePromises (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:693:18)
          at Async._drainQueue (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:133:16)
          at Async._drainQueues (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:143:10) code: 'ETELEGRAM', response: [Object] },
     _rejectionHandler0: [Function],
     _promise0: undefined,
     _receiver0: undefined,
     _cancellationParent: undefined,
     _branchesRemainingToCancel: 1,
     _onCancelField: undefined } }  with reason  Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 92
    at BaseError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:10:5)
    at TelegramError (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/errors.js:56:5)
    at request.then.err (/home/Telegram-Bot-Node/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
    at tryCatcher (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/Telegram-Bot-Node/node_modules/bluebird/js/release/async.js:143:10)

But if i want to search normal song : **/yt alicia kara** - stay and the another songs is no issue

**Comment by CapacitorSet** [comment]
I think I got it: when the title contains `]`, Telegram complains because it thinks it's closing the Markdown link. However, I'll look at it tomorrow.

Can you please open a new issue? It's a different problem than the one discussed here.

**Comment by koodoxz** [comment]
ok let me open in new issue
